version: '3.8'
services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users-codebuddy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./authorization-service
      dockerfile: ./Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - auth-db

  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chats-codebuddy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - chat-db-data:/var/lib/postgresql/data

  chat-service:
    build:
      context: ./chat-service
      dockerfile: ./Dockerfile
    ports:
      - '8082:8080'
    depends_on:
      - chat-db

  gateway-service:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'

volumes:
  auth-db-data:
  chat-db-data: