spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: test
#    password: test

    url: jdbc:postgresql://chat-db:5432/chats-codebuddy
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true

server:
  port: 8082